[package]
name = "functions_from_rust_4_kivy"
version = "0.1.0"
authors = ["Santo Kalayil <santokalayil@gmail.com>"]
edition = "2018"

[lib]
name = "functions_from_rust_4_kivy"
crate-type = ["dylib"]

[dependencies]
cpython = { git = "https://github.com/dgrunwald/rust-cpython" }
sqlite = "0.26.0"